from flask import request, jsonify
from . import auth_bp
from supabase import create_client
from dotenv import load_dotenv
import os

load_dotenv()

supabase = create_client(
    os.environ["SUPABASE_URL"],
    os.environ["SUPABASE_SERVICE_ROLE_KEY"]
)

@auth_bp.route("/login", methods=["POST"])
def login():
    data = request.json
    email = data.get("email")
    password = data.get("password")

    if not email or not password:
        return jsonify({"error": "Missing credentials"}), 400

    try:
        res = supabase.auth.sign_in_with_password({
            "email": email,
            "password": password
        })

        return jsonify({
            "access_token": res.session.access_token,
            "user": res.user.email
        })

    except Exception:
        return jsonify({"error": "Invalid email or password"}), 401
    
@auth_bp.route("/register", methods=["POST"])
def register():
    data = request.json
    email = data.get("email")
    password = data.get("password")
    name = data.get("name")
    userId = data.get("userId")  # self-chosen

    if not email or not password or not userId:
        return jsonify({"error": "Missing credentials"}), 400

    # 1️⃣ Check if userId already exists
    existing = supabase.table("user").select("userId").eq("userId", userId).execute()
    if existing.data and len(existing.data) > 0:
        return jsonify({"error": "userId already taken"}), 400

    try:
        # 2️⃣ Create Auth user
        res = supabase.auth.sign_up({
            "email": email,
            "display_name": name,
            "password": password
        })

        if not res.user:
            return jsonify({"error": "Failed to create user"}), 500

        authId = res.user.id  # UUID generated by Supabase Auth

        # 3️⃣ Insert into custom user table
        supabase.table("user").insert({
            "userId": userId,    # self-chosen PK
            "authId": authId,    # FK to auth.users.id
            "email": email,
            "name": name,
            "created_at": "now()",
            "password": password
        }).execute()

        return jsonify({
            "message": "User registered successfully",
            "user": res.user.email,
            "userId": userId
        }), 201

    except Exception as e:
        return jsonify({"error": str(e)}), 400
